# Задание 1. Первичный анализ и предобработка

### Загрузите датасет

### Выведите информацию о датасете

In [10]:
import pandas as pd
import numpy as np
import math

In [13]:
Kinopoisk = pd.read_csv('Kinopoisk.csv',error_bad_lines=False,sep=';')

In [14]:
Kinopoisk

       Год начала  Год окончания  ... Длительность (мин) Средний рейтинг
0            1982            NaN  ...               62.0           7,767
1            2005            NaN  ...               86.0           5,895
2            2001            NaN  ...               90.0           5,608
3            2003            NaN  ...              120.0           8,345
4            1997            NaN  ...               91.0           7,172
...           ...            ...  ...                ...             ...
45649        1999            NaN  ...               96.0           7,735
45650        2008            NaN  ...              103.0           6,219
45651        2004            NaN  ...               22.0           7,416
45652        2004            NaN  ...               45.0            7,61
45653        1993            NaN  ...              100.0           6,554

[45654 rows x 12 columns]

### Какой размер датасета (число столбцов и колонок)

In [15]:
Kinopoisk.shape

(45654, 12)

### Выведите первые 20 строк датасета

In [16]:
Kinopoisk.head(20)

    Год начала  Год окончания  ... Длительность (мин) Средний рейтинг
0         1982            NaN  ...               62.0           7,767
1         2005            NaN  ...               86.0           5,895
2         2001            NaN  ...               90.0           5,608
3         2003            NaN  ...              120.0           8,345
4         1997            NaN  ...               91.0           7,172
5         2002            NaN  ...               89.0           7,028
6         2006            NaN  ...               89.0           6,831
7         2005            NaN  ...               90.0           4,695
8         2006            NaN  ...               90.0           6,918
9         1998            NaN  ...               90.0           6,725
10        1996         2007.0  ...               90.0            7,22
11        1998            NaN  ...              113.0           7,148
12        2005            NaN  ...               96.0           6,785
13        1997            NaN  ...               93.0           5,445
14        2006            NaN  ...                0.0           3,325
15        2006            NaN  ...              180.0           5,727
16        2006            NaN  ...               90.0           4,529
17        1988         1999.0  ...               97.0           6,085
18        2002         2008.0  ...               46.0           7,832
19        2006            NaN  ...               93.0           7,674

[20 rows x 12 columns]

### Выведите последние 10 строк датасета

In [17]:
Kinopoisk.tail(10)

       Год начала  Год окончания  ... Длительность (мин) Средний рейтинг
45644        1984         1988.0  ...               22.0           7,948
45645        2007            NaN  ...               89.0           5,295
45646        2004            NaN  ...                0.0           7,059
45647        1988            NaN  ...               61.0           7,717
45648        1998            NaN  ...              104.0           6,605
45649        1999            NaN  ...               96.0           7,735
45650        2008            NaN  ...              103.0           6,219
45651        2004            NaN  ...               22.0           7,416
45652        2004            NaN  ...               45.0            7,61
45653        1993            NaN  ...              100.0           6,554

[10 rows x 12 columns]

###  Проведите анализ на пропуски и дубликаты. Стоит ли удалять пропуски или заменять?

In [18]:
Kinopoisk.duplicated().sum()

0

In [19]:
Kinopoisk.isna().sum()

Год начала                 0
Год окончания          42938
Тип                        0
Жанр                     185
Жанр 2                 12306
Жанр 3                 27489
ID                         0
Страна производства       23
Название                   0
Количество голосов         0
Длительность (мин)       953
Средний рейтинг            0
dtype: int64

In [20]:
Kinopoisk.loc[Kinopoisk['Страна производства'].isna()]

       Год начала  Год окончания  ... Длительность (мин) Средний рейтинг
3853         2008            NaN  ...                NaN           6,542
10777        2014            NaN  ...               90.0           2,927
14620        2014            NaN  ...               43.0           6,904
14650        2014            NaN  ...                4.0            6,86
14895        2014            NaN  ...               30.0           5,284
15322        2014            NaN  ...                NaN           7,041
27008        2015            NaN  ...               82.0           2,653
30396        2019            NaN  ...               97.0           7,091
30657        2019            NaN  ...               71.0           4,985
30865        2015            NaN  ...               83.0            3,67
31581        2020            NaN  ...               66.0           6,959
31590        2019            NaN  ...                NaN           7,014
31727        2015            NaN  ...                NaN           7,133
32040        2017            NaN  ...               97.0           5,153
32119        2016         2019.0  ...               30.0           6,742
36227        2015            NaN  ...                NaN            6,36
36728        2017            NaN  ...               96.0            4,78
36851        2016            NaN  ...                NaN           3,732
40588        2019            NaN  ...               92.0           3,933
40821        2018            NaN  ...               95.0            7,61
40993        2018            NaN  ...               30.0           6,266
41965        2019            NaN  ...               58.0           6,864
42817        2005            NaN  ...                0.0           7,931

[23 rows x 12 columns]

In [21]:
Kinopoisk.dropna(subset=['Страна производства'],inplace=True)

In [22]:
Kinopoisk.isna().sum()

Год начала                 0
Год окончания          42916
Тип                        0
Жанр                     181
Жанр 2                 12291
Жанр 3                 27468
ID                         0
Страна производства        0
Название                   0
Количество голосов         0
Длительность (мин)       947
Средний рейтинг            0
dtype: int64

### Поменяйте типы данных, если нужно

### Приведите дату к правильному формату

# Задание 2. Срезы данных

### Сделайте срезы данных  по различным условиям (минимум 3)

# Задание 3. Анализ данных

Ваша задача провести первичный анализ данных на основании придуманных вами критериев. Для этого можно воспользоваться группировкой, агрегацией и срезами данных

###  Проведите минимум 3 различных группировки по разным категориям

### Создайте несколько сводных таблиц

### Опишите ваши выводы при первичном анализе